import {handleManualBooking} from '../../supabase/functions/send-manual-booking/handler.ts';
const id='11111111-1111-4111-8111-111111111111';
function assert(v:unknown):asserts v {if(!v)throw new Error('Assertion failed');}
function fixture(o:{dry?:boolean;internal?:boolean;ineligible?:boolean;disconnected?:boolean;duplicate?:boolean;timeout?:boolean;expired?:boolean;reject?:boolean}={}){
 const writes:any[]=[],calls:string[]=[];
 const reads:any[]=[{id,user_id:'owner',name:'Teste',phone:'55999999999',is_active:true,end_date:'2099-01-01'},[{eligible:!o.ineligible}],{booking_link_slug:'consultoria'},{owner_user_id:'owner'},null,{id:'template',title:'Consulta',body:'Olá {nome}, acesse {booking_link}'},{id:'link',token:'test-token',expires_at:o.expired?'2000-01-01':null},o.duplicate?[{id:'old'}]:[]];
 function builder(table:string){let op='read',payload:any;const chain:any=new Proxy({},{get(_,prop){if(prop==='then')return(resolve:any)=>{if(op==='read')return Promise.resolve({data:reads.shift(),error:null}).then(resolve);writes.push({table,op,payload});return Promise.resolve({data:op==='insert'?{id:'reservation'}:null,error:null}).then(resolve);};return(arg:any)=>{if(prop==='insert'||prop==='update'){op=String(prop);payload=arg;}return chain;};}});return chain;}
 const deps:any={guard:async()=>({ok:true,caller:o.internal?{kind:'internal'}:{kind:'admin',userId:'owner'}}),db:()=>({from:builder,rpc:()=>Promise.resolve({data:reads.shift(),error:null})}),env:()=> 'configured',fetch:async(url:string,init:any)=>{calls.push(url.endsWith('/status')?'status':'send');if(url.endsWith('/status'))return new Response(JSON.stringify({connected:!o.disconnected}));if(o.timeout)throw new Error('timeout');assert(JSON.parse(init.body).message.includes('/agendar/consultoria?bt=test-token'));return new Response(JSON.stringify(o.reject?{error:'rejected'}:{messageId:'provider-id'}),{status:o.reject?400:200});}};
 return{writes,calls,run:()=>handleManualBooking(new Request('https://app.test',{method:'POST',body:JSON.stringify({clientId:id,dryRun:!!o.dry,send:!o.dry})}),deps)};
}
Deno.test('booking preflight does not send, create link or reserve',async()=>{const f=fixture({dry:true});assert((await f.run()).ok);assert(!f.writes.length&&f.calls.join()==='status');});
Deno.test('booking rejects cron before database',async()=>{const f=fixture({internal:true});assert((await f.run()).status===403);assert(!f.writes.length&&!f.calls.length);});
Deno.test('booking respects consultation entitlement',async()=>{const f=fixture({ineligible:true});assert((await f.run()).status===400);assert(!f.writes.length&&!f.calls.length);});
Deno.test('booking expired link fails preflight without reservation',async()=>{const f=fixture({dry:true,expired:true});assert((await f.run()).status===409);assert(!f.writes.length&&!f.calls.length);});
Deno.test('booking duplicate is blocked',async()=>{const f=fixture({duplicate:true});assert((await f.run()).status===409);assert(!f.writes.length&&!f.calls.length);});
Deno.test('booking disconnected provider never creates reservation',async()=>{const f=fixture({disconnected:true});assert((await f.run()).status===503);assert(!f.writes.length);});
Deno.test('booking acceptance records reservation before accepted state',async()=>{const f=fixture();assert((await f.run()).ok);assert(f.writes[0].table==='manual_booking_sends');assert(f.writes[1].payload.status==='sent');assert(f.calls.join()==='status,send');});
Deno.test('booking timeout keeps reservation and never retries',async()=>{const f=fixture({timeout:true});assert((await f.run()).status===503);assert(f.writes.length===1&&f.calls.join()==='status,send');});
Deno.test('booking explicit refusal records failed, not sent',async()=>{const f=fixture({reject:true});assert((await f.run()).status===502);assert(f.writes.at(-1).payload.status==='failed');});
