-- Metanóia: o formulário único do programa e o plano de onboarding.
--
-- Gerado por scripts/gerar-migracao-metanoia.ts a partir de
-- src/lib/metanoiaAnamnese.ts (Anamnese Completa + blocos do app + seção
-- comportamental). Não edite as perguntas aqui: mude a fonte e gere de novo.
--
-- Idempotente: só grava o que ainda não existe. Num banco montado do zero o
-- dono não existe em auth.users e o bloco de conteúdo é pulado.

alter table public.clients add column if not exists asaas_payment_link_id text;
alter table public.clients add column if not exists asaas_payment_link_url text;
create index if not exists clients_asaas_payment_link_id_idx
  on public.clients (asaas_payment_link_id) where asaas_payment_link_id is not null;

do $$
declare
  v_owner uuid := 'c05878bf-0f7a-4d7f-8f96-7ca33c2d5a9b';
  v_form  uuid := '5c4f1b2e-9d3a-4e8b-8f6a-2a7c1d9e0b11';
begin
  if not exists (select 1 from auth.users where id = v_owner) then
    raise notice 'metanoia: dono % ausente neste banco, conteúdo não semeado', v_owner;
    return;
  end if;

  perform set_config('request.jwt.claims', json_build_object('sub', v_owner, 'role', 'authenticated')::text, true);

  -- 1. O plano, fora da vitrine (/plans lista só os ativos). O checkout lê pelo slug.
  if not exists (select 1 from public.onboarding_plans where slug = 'metanoia') then
    insert into public.onboarding_plans
      (slug, category, periodicity, name, description, duration_months, consultations_count, consultation_interval_weeks, checkin_frequency, payment_link, price, order_index, is_active)
    values
      ('metanoia', 'consultas', 'trimestral', 'Metanóia', 'Programa de 12 semanas de comportamento alimentar para corredores: 3 consultas, Pausa da Semana e acompanhamento no WhatsApp.', 3, 3, 4, 'weekly', null, 1297.00, 100, false);
  end if;

  -- 2. O formulário único, com id fixo, publicado como a tela publicaria.
  if not exists (select 1 from public.anamnese_forms where id = v_form) then
    insert into public.anamnese_forms (id, user_id, title, description, is_active)
    values (v_form, v_owner, 'Anamnese Completa · Metanóia', 'Esta é a sua avaliação inicial do Metanóia. Ela leva cerca de 15 minutos e junta duas partes: o que precisamos para montar o seu plano alimentar e como está, hoje, a sua relação com a comida. Responda com calma e sem se julgar. Não existe resposta certa, existe a sua.', true);

    insert into public.anamnese_questions
      (form_id, section, question_text, question_type, canonical_type, question_key, options, scale_min, scale_max, is_required, order_index, has_comment_field, comment_field_label, comment_field_required, conditional_logic, config, domain)
    values
      (v_form, '1. Identificação e objetivos', 'Nome completo', 'text', 'short_text', 'nome_completo', null, null, null, true, 0, false, null, false, null, '{"prefill_from_profile":"full_name"}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'Data de nascimento', 'date', 'date', 'data_nascimento', null, null, null, true, 1, false, null, false, null, '{"prefill_from_profile":"birth_date"}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'WhatsApp (DDD + número)', 'text', 'short_text', 'whatsapp', null, null, null, true, 2, false, null, false, null, '{"prefill_from_profile":"phone","input":"phone"}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'Sexo para fins de avaliação nutricional e hormonal', 'select', 'single_select', 'sexo', '["Masculino","Feminino","Intersexo","Prefiro não informar"]'::jsonb, null, null, true, 3, false, null, false, null, '{"prefill_from_profile":"gender"}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'Peso e altura atuais', 'field_group', null, 'peso_altura', null, null, null, true, 4, false, null, false, null, '{"fields":[{"key":"peso_kg","label":"Peso","type":"number","unit":"kg","required":true,"min":20,"max":300,"step":0.1,"warn_below":35,"warn_above":200,"prefill_from_profile":"current_weight"},{"key":"altura_cm","label":"Altura","type":"number","unit":"cm","required":true,"min":120,"max":230,"warn_below":130,"warn_above":220,"prefill_from_profile":"height"}]}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'Como é o seu dia fora do treino?', 'select', 'single_select', 'nivel_atividade_diaria', '["Sentado a maior parte do dia","Sentado, com deslocamentos","Em pé ou caminhando boa parte do dia","Trabalho físico"]'::jsonb, null, null, true, 5, false, null, false, null, null, null),
      (v_form, '1. Identificação e objetivos', 'Mudança de peso nos últimos três meses', 'field_group', null, 'mudanca_peso', null, null, null, false, 6, false, null, false, null, '{"fields":[{"key":"mudanca","label":"O que ocorreu?","type":"select","required":true,"options":["Permaneceu praticamente estável","Diminuiu menos de 2 kg","Diminuiu entre 2 e 5 kg","Diminuiu mais de 5 kg","Aumentou menos de 2 kg","Aumentou entre 2 e 5 kg","Aumentou mais de 5 kg","Não sei informar"]},{"key":"planejada","label":"Essa mudança foi planejada?","type":"select","options":["Sim","Não","Parcialmente"],"show_if":{"key":"self.mudanca","op":"not_in","value":["Permaneceu praticamente estável","Não sei informar"]}}]}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'Objetivos atuais', 'field_group', null, 'objetivos', null, null, null, true, 7, false, null, false, null, '{"fields":[{"key":"selecionados","label":"Selecione seus objetivos","type":"multiselect","required":true,"options":["Melhorar minha performance","Preparar-me para uma prova","Perder gordura corporal","Manter o peso","Ganhar massa muscular","Ganhar peso","Melhorar minha recuperação","Recuperar-me de uma lesão","Melhorar minha saúde","Melhorar sintomas gastrointestinais","Outro"]},{"key":"outro","label":"Qual outro objetivo?","type":"text","show_if":{"key":"self.selecionados","op":"includes","value":"Outro"}},{"key":"prioritario","label":"Qual é o objetivo mais importante neste momento?","type":"select_from","from":"selecionados","required":true}]}'::jsonb, null),
      (v_form, '1. Identificação e objetivos', 'Meta de peso ou composição corporal', 'field_group', null, 'meta_peso_composicao', null, null, null, false, 8, false, null, false, null, '{"fields":[{"key":"meta","label":"Qual é a sua meta?","type":"select","options":["Perder gordura","Manter o peso","Ganhar massa muscular","Não tenho meta de peso"],"required":true},{"key":"peso_alvo_kg","label":"Peso que gostaria de alcançar","type":"number","unit":"kg","min":30,"max":250,"step":0.1,"show_if":{"key":"self.meta","op":"in","value":["Perder gordura","Ganhar massa muscular"]}},{"key":"prazo","label":"Em quanto tempo?","type":"text","placeholder":"Ex.: até a prova de novembro","show_if":{"key":"self.meta","op":"not_equals","value":"Não tenho meta de peso"}}]}'::jsonb, null),
      (v_form, '2. Treinamento e prova-alvo', 'Modalidade e experiência', 'field_group', null, 'modalidade_experiencia', null, null, null, true, 9, false, null, false, null, '{"fields":[{"key":"modalidades","label":"Modalidade(s)","type":"multiselect","required":true,"options":["Corrida de rua","Trail running","Triatlo","Duatlo","Ciclismo","Natação","Outra modalidade de endurance"]},{"key":"outra_modalidade","label":"Qual outra modalidade?","type":"text","show_if":{"key":"self.modalidades","op":"includes","value":"Outra modalidade de endurance"}},{"key":"tempo_pratica","label":"Tempo de prática","type":"select","required":true,"options":["Menos de 6 meses","De 6 meses a 1 ano","De 1 a 3 anos","De 3 a 5 anos","Mais de 5 anos"]}]}'::jsonb, null),
      (v_form, '2. Treinamento e prova-alvo', 'Semana habitual de treinamento', 'training_week', null, 'semana_treino', null, null, null, true, 10, false, null, false, null, '{"detailed":true,"modalities":["Corrida","Musculação","Ciclismo","Natação","Mobilidade","Outra"],"sessionTypes":["Descanso","Regenerativo","Corrida leve","Corrida longa","Intervalado","Ritmo ou tempo run","Limiar","Subidas","Treino progressivo","Musculação","Técnica","Transição","Competição","Outro"],"sessionFields":["start_time","modality","session_type","duration_minutes","distance_km","rpe","notes"],"allowMultiplePerDay":true,"allowDuplicate":true}'::jsonb, null),
      (v_form, '2. Treinamento e prova-alvo', 'Estabilidade da rotina de treinamento', 'field_group', null, 'estabilidade_rotina', null, null, null, false, 11, false, null, false, null, '{"fields":[{"key":"estabilidade","label":"Como é sua rotina?","type":"select","required":true,"options":["Minha semana costuma ser quase sempre assim","Muda um pouco a cada semana","Muda bastante conforme a planilha","Estou iniciando uma nova fase de treinamento","Estou reduzindo a carga","Estou retornando de lesão ou pausa"]},{"key":"mudanca_prevista","label":"Existe alguma mudança importante prevista para as próximas quatro semanas?","type":"textarea"}]}'::jsonb, null),
      (v_form, '2. Treinamento e prova-alvo', 'Prova-alvo', 'field_group', null, 'prova_alvo', null, null, null, false, 12, false, null, false, null, '{"fields":[{"key":"possui","label":"Você possui alguma prova-alvo?","type":"select","required":true,"options":["Sim","Não"]},{"key":"modalidade","label":"Modalidade","type":"text","show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"nome","label":"Nome da prova (opcional)","type":"text","show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"distancia","label":"Distância","type":"text","show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"data","label":"Data","type":"date","show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"duracao_estimada","label":"Duração estimada","type":"text","show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"prioridade","label":"Prioridade da prova","type":"select","options":["A","B","C"],"show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"ja_fez_carbloading","label":"Já realizou carbloading antes?","type":"select","options":["Sim","Não","Não sei o que é"],"show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"desconforto_gi","label":"Teve desconforto gastrointestinal em provas anteriores?","type":"select","options":["Sim","Não"],"show_if":{"key":"self.possui","op":"equals","value":"Sim"}},{"key":"desconforto_gi_desc","label":"Descreva o desconforto","type":"textarea","show_if":{"key":"self.desconforto_gi","op":"equals","value":"Sim"}}]}'::jsonb, null),
      (v_form, '3. Alimentação relacionada ao treino', 'Alimentação antes dos treinos matinais', 'field_group', null, 'pre_treino_matinal', null, null, null, false, 13, false, null, false, null, '{"fields":[{"key":"situacao","label":"Quando você treina pela manhã, o que normalmente acontece antes do treino?","type":"select","required":true,"options":["Não como nada","Faço um lanche pequeno","Faço uma refeição completa","Consumo apenas café","Consumo apenas líquidos ou suplemento","Depende do tipo de treino","Não treino pela manhã"]},{"key":"horario","label":"Horário aproximado","type":"time","show_if":{"key":"self.situacao","op":"in","value":["Faço um lanche pequeno","Faço uma refeição completa","Depende do tipo de treino"]}},{"key":"alimentos_bebidas_quantidades","label":"Alimentos, bebidas, quantidades e porções","type":"textarea","placeholder":"Ex.: 1 pão francês com queijo, 200 ml de café com leite, 1 banana...","show_if":{"key":"self.situacao","op":"in","value":["Faço um lanche pequeno","Faço uma refeição completa","Depende do tipo de treino"]}}]}'::jsonb, null),
      (v_form, '3. Alimentação relacionada ao treino', 'Tempo entre a última refeição e o treino', 'field_group', null, 'intervalo_refeicao_treino', null, null, null, false, 14, false, null, false, null, '{"fields":[{"key":"intervalo","label":"Quanto tempo, normalmente?","type":"select","required":true,"options":["Menos de 30 minutos","Entre 30 e 60 minutos","Entre 1 e 2 horas","Entre 2 e 3 horas","Mais de 3 horas","Varia conforme o dia","Normalmente treino sem comer"]},{"key":"quando_varia","label":"Em quais treinos ou horários isso muda?","type":"text","show_if":{"key":"self.intervalo","op":"equals","value":"Varia conforme o dia"}}]}'::jsonb, null),
      (v_form, '3. Alimentação relacionada ao treino', 'Alimentação durante treinos mais longos', 'field_group', null, 'intra_treino', null, null, null, false, 15, false, null, false, null, '{"fields":[{"key":"consumos","label":"O que costuma consumir?","type":"multiselect","required":true,"options":["Não consumo nada","Água","Bebida esportiva","Gel de carboidrato","Doce de leite","Rapadura","Paçoca","Frutas","Frutas secas","Eletrólitos ou cápsula de sal","Outro","Ainda não realizo treinos que necessitem alimentação"]}]}'::jsonb, null),
      (v_form, '3. Alimentação relacionada ao treino', 'Hidratação e transpiração', 'field_group', null, 'hidratacao', null, null, null, false, 16, false, null, false, null, '{"fields":[{"key":"liquidos_dia","label":"Quantidade média de líquidos por dia","type":"select","required":true,"options":["Menos de 1 litro","Entre 1 e 2 litros","Entre 2 e 3 litros","Mais de 3 litros","Não sei informar"]},{"key":"transpiracao","label":"Como considera sua transpiração","type":"select","options":["Baixa","Moderada","Alta","Muito alta","Não sei"]},{"key":"sinais","label":"Sinais durante ou depois dos treinos","type":"multiselect","options":["Muita sede","Dor de cabeça","Tontura","Cãibras","Marcas brancas de sal na roupa ou pele","Urina muito escura","Nenhum desses sinais"]}]}'::jsonb, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Sintomas gastrointestinais', 'symptom_grid', null, 'sintomas_gi', null, null, null, false, 17, false, null, false, null, '{"symptoms":["Distensão abdominal","Excesso de gases","Refluxo ou azia","Náusea","Dor abdominal","Diarreia","Constipação","Urgência para evacuar","Sensação de digestão lenta","Arroto ou regurgitação","Nenhum"],"noneOption":"Nenhum","moments":["Fora dos treinos","Antes do treino","Durante o treino","Depois do treino"],"frequencies":["Raramente","Às vezes","Frequentemente","Sempre"],"intensities":["Leve","Moderada","Forte"]}'::jsonb, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Diagnósticos e exames', 'field_group', null, 'diagnosticos_exames', null, null, null, false, 18, false, null, false, null, '{"fields":[{"key":"diagnosticos","label":"Você possui diagnóstico, acompanhamento médico ou exames recentes com alterações?","type":"multiselect","required":true,"options":["Anemia ou deficiência de ferro","Diabetes ou alteração da glicemia","Hipertensão","Alteração de colesterol ou triglicerídeos","Doença gastrointestinal","Doença da tireoide","Doença renal","Doença hepática","Alergia alimentar diagnosticada","Transtorno alimentar atual ou anterior","Outro diagnóstico","Não possuo","Não sei informar"]},{"key":"descricao","label":"Descrição curta","type":"textarea","show_if":{"key":"self.diagnosticos","op":"includes_any","value":["Anemia ou deficiência de ferro","Diabetes ou alteração da glicemia","Hipertensão","Alteração de colesterol ou triglicerídeos","Doença gastrointestinal","Doença da tireoide","Doença renal","Doença hepática","Alergia alimentar diagnosticada","Transtorno alimentar atual ou anterior","Outro diagnóstico"]}},{"key":"data_diagnostico","label":"Data aproximada do diagnóstico","type":"date","show_if":{"key":"self.diagnosticos","op":"includes_any","value":["Anemia ou deficiência de ferro","Diabetes ou alteração da glicemia","Hipertensão","Alteração de colesterol ou triglicerídeos","Doença gastrointestinal","Doença da tireoide","Doença renal","Doença hepática","Alergia alimentar diagnosticada","Transtorno alimentar atual ou anterior","Outro diagnóstico"]}},{"key":"data_exames","label":"Data dos exames mais recentes","type":"date","show_if":{"key":"self.diagnosticos","op":"includes_any","value":["Anemia ou deficiência de ferro","Diabetes ou alteração da glicemia","Hipertensão","Alteração de colesterol ou triglicerídeos","Doença gastrointestinal","Doença da tireoide","Doença renal","Doença hepática","Alergia alimentar diagnosticada","Transtorno alimentar atual ou anterior","Outro diagnóstico"]}},{"key":"anexos","label":"Anexar exames (opcional)","type":"file_upload"}]}'::jsonb, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Medicamentos', 'field_group', null, 'medicamentos', null, null, null, false, 19, false, null, false, null, '{"fields":[{"key":"usa","label":"Você utiliza algum medicamento de forma contínua?","type":"select","required":true,"options":["Sim","Não"]},{"key":"lista","label":"Medicamentos","type":"structured_list","addLabel":"Adicionar medicamento","show_if":{"key":"self.usa","op":"equals","value":"Sim"},"fields":[{"key":"nome","label":"Nome","type":"text","required":true},{"key":"dose","label":"Dose (se souber)","type":"text"},{"key":"horario","label":"Horário","type":"text"},{"key":"motivo","label":"Motivo de uso","type":"text"}]}]}'::jsonb, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Saúde e recuperação', 'field_group', null, 'saude_recuperacao', null, null, null, false, 20, false, null, false, null, '{"fields":[{"key":"situacoes","label":"Como está sua saúde e recuperação?","type":"multiselect","required":true,"options":["Estou lesionado","Tenho uma dor persistente","Já tive fratura por estresse","Tenho lesões recorrentes","Minha recuperação está mais lenta","Tenho dor muscular por vários dias","Fico doente com frequência","Meu desempenho caiu recentemente","Estou me recuperando normalmente","Nenhuma das opções"]},{"key":"descricao","label":"Qual é a lesão, dor ou problema?","type":"textarea","show_if":{"key":"self.situacoes","op":"includes_any","value":["Estou lesionado","Tenho uma dor persistente","Já tive fratura por estresse","Tenho lesões recorrentes","Minha recuperação está mais lenta","Tenho dor muscular por vários dias","Fico doente com frequência","Meu desempenho caiu recentemente"]}},{"key":"ha_quanto_tempo","label":"Há quanto tempo?","type":"text","show_if":{"key":"self.situacoes","op":"includes_any","value":["Estou lesionado","Tenho uma dor persistente","Já tive fratura por estresse","Tenho lesões recorrentes","Minha recuperação está mais lenta","Tenho dor muscular por vários dias","Fico doente com frequência","Meu desempenho caiu recentemente"]}},{"key":"acompanhamento","label":"Está em acompanhamento profissional?","type":"select","options":["Sim","Não"],"show_if":{"key":"self.situacoes","op":"includes_any","value":["Estou lesionado","Tenho uma dor persistente","Já tive fratura por estresse","Tenho lesões recorrentes","Minha recuperação está mais lenta","Tenho dor muscular por vários dias","Fico doente com frequência","Meu desempenho caiu recentemente"]}}]}'::jsonb, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Sinais percebidos nos últimos três meses', 'multiselect', 'multi_select', 'sinais_tres_meses', '["Fadiga persistente","Fome muito elevada","Perda de apetite","Irritabilidade ou alteração de humor","Dificuldade para manter o ritmo dos treinos","Queda de força","Piora do sono","Sensação frequente de frio","Diminuição da libido","Perda de peso não planejada","Lesões frequentes","Doenças frequentes","Preocupação excessiva com peso ou alimentos","Restrição voluntária de carboidratos","Nenhum desses sinais"]'::jsonb, null, null, false, 21, false, null, false, null, null, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Ciclo menstrual', 'field_group', null, 'ciclo_menstrual', null, null, null, false, 22, false, null, false, '{"show_if":{"key":"sexo","op":"in","value":["Feminino","Intersexo"]}}'::jsonb, '{"fields":[{"key":"situacao","label":"Como está seu ciclo menstrual atualmente?","type":"select","options":["Regular, sem alterações","Irregular","Fiquei três meses ou mais sem menstruar","A menstruação parou após aumento dos treinos ou perda de peso","Tenho fluxo menstrual muito intenso","Utilizo anticoncepcional hormonal e não consigo avaliar","Estou na menopausa","Não se aplica","Prefiro não responder"]},{"key":"ultima_menstruacao","label":"Quando ocorreu sua última menstruação espontânea? (mês/ano ou data)","type":"text","show_if":{"key":"self.situacao","op":"in","value":["Irregular","Fiquei três meses ou mais sem menstruar","A menstruação parou após aumento dos treinos ou perda de peso"]}}]}'::jsonb, null),
      (v_form, '4. Saúde, sintomas e recuperação', 'Sono', 'field_group', null, 'sono', null, null, null, false, 23, false, null, false, null, '{"fields":[{"key":"horas","label":"Horas de sono por noite","type":"select","options":["Menos de 5 horas","Entre 5 e 6 horas","Entre 6 e 7 horas","Entre 7 e 8 horas","Mais de 8 horas"]},{"key":"qualidade","label":"Qualidade do sono","type":"select","options":["Muito ruim","Ruim","Regular","Boa","Muito boa"]},{"key":"sinais","label":"Outros sinais","type":"multiselect","options":["Dificuldade para dormir","Acordo várias vezes","Acordo cansado","Sinto fome durante a noite","Tenho refluxo à noite","Nenhum"]}]}'::jsonb, null),
      (v_form, '5. Preferências e restrições', 'Restrições alimentares', 'field_group', null, 'restricoes', null, null, null, false, 24, false, null, false, null, '{"fields":[{"key":"tipos","label":"Você possui alguma restrição?","type":"multiselect","required":true,"options":["Alergia alimentar diagnosticada","Intolerância à lactose","Doença celíaca","Vegetarianismo","Veganismo","Restrição religiosa","Retirei um alimento por desconforto","Retirei um alimento por preferência","Nenhuma","Outra"]},{"key":"alimento_grupo","label":"Qual alimento ou grupo alimentar?","type":"text","show_if":{"key":"self.tipos","op":"includes_any","value":["Alergia alimentar diagnosticada","Intolerância à lactose","Doença celíaca","Vegetarianismo","Veganismo","Restrição religiosa","Retirei um alimento por desconforto","Retirei um alimento por preferência","Outra"]}},{"key":"reacao_motivo","label":"Qual reação ou motivo?","type":"text","show_if":{"key":"self.tipos","op":"includes_any","value":["Alergia alimentar diagnosticada","Intolerância à lactose","Doença celíaca","Vegetarianismo","Veganismo","Restrição religiosa","Retirei um alimento por desconforto","Retirei um alimento por preferência","Outra"]}},{"key":"diagnostico_profissional","label":"Existe diagnóstico profissional?","type":"select","options":["Sim","Não","Não se aplica"],"show_if":{"key":"self.tipos","op":"includes_any","value":["Alergia alimentar diagnosticada","Intolerância à lactose","Doença celíaca","Vegetarianismo","Veganismo","Restrição religiosa","Retirei um alimento por desconforto","Retirei um alimento por preferência","Outra"]}}]}'::jsonb, null),
      (v_form, '5. Preferências e restrições', 'Preferências e alimentos que devem ser evitados', 'field_group', null, 'preferencias', null, null, null, false, 25, false, null, false, null, '{"fields":[{"key":"gosta","label":"Alimentos de que gosta e gostaria de manter no plano","type":"chips"},{"key":"evitar","label":"Alimentos de que não gosta, não tolera ou não deseja receber no plano","type":"chips"}]}'::jsonb, null),
      (v_form, '5. Preferências e restrições', 'Fome e comportamento alimentar', 'field_group', null, 'fome_comportamento', null, null, null, false, 26, false, null, false, null, '{"fields":[{"key":"padroes","label":"Como está sua fome e seu comportamento alimentar?","type":"multiselect","required":true,"options":["Sinto pouca fome","Minha fome é adequada","Sinto muita fome entre as refeições","Sinto muita fome à noite","Tenho vontade frequente de doces","Belisco sem perceber","Como além da saciedade","Pulo refeições por falta de tempo","Evito comer para controlar o peso","Tenho episódios de perda de controle","Nenhuma dificuldade relevante"]},{"key":"quando","label":"Em qual horário ou situação isso ocorre com mais frequência?","type":"text","show_if":{"key":"self.padroes","op":"includes_any","value":["Sinto pouca fome","Sinto muita fome entre as refeições","Sinto muita fome à noite","Tenho vontade frequente de doces","Belisco sem perceber","Como além da saciedade","Pulo refeições por falta de tempo","Evito comer para controlar o peso","Tenho episódios de perda de controle"]}}]}'::jsonb, null),
      (v_form, '6. Alimentação habitual', 'Alimentação em um dia habitual', 'meal_plan_editor', null, 'alimentacao_habitual', null, null, null, true, 27, false, null, false, null, '{"simpleMode":true,"units":["Gramas","Colher","Colher de sopa","Colher de chá","Concha","Unidade","Fatia","Copo","Xícara","ml"],"defaultMeals":["Café da manhã","Lanche da manhã","Almoço","Lanche da tarde","Jantar","Ceia"]}'::jsonb, null),
      (v_form, '6. Alimentação habitual', 'Diferenças entre os dias', 'field_group', null, 'diferencas_entre_dias', null, null, null, false, 28, false, null, false, null, '{"fields":[{"key":"mudancas","label":"Sua alimentação muda conforme o tipo de treino ou o dia da semana?","type":"multiselect","required":true,"options":["Como mais nos dias de longão","Como mais nos dias de treino intenso","Como menos nos dias de descanso","Mudo apenas o pré-treino","Mudo apenas o pós-treino","Como diferente aos finais de semana","Como diferente quando treino em outro horário","Minha alimentação é praticamente igual todos os dias","Não sei avaliar"]},{"key":"o_que_muda","label":"Informe apenas o que normalmente muda (alimento, quantidade, horário, dia/tipo de treino)","type":"textarea","show_if":{"key":"self.mudancas","op":"includes_any","value":["Como mais nos dias de longão","Como mais nos dias de treino intenso","Como menos nos dias de descanso","Mudo apenas o pré-treino","Mudo apenas o pós-treino","Como diferente aos finais de semana","Como diferente quando treino em outro horário"]}}]}'::jsonb, null),
      (v_form, '6. Alimentação habitual', 'Suplementos e produtos esportivos', 'field_group', null, 'suplementos', null, null, null, false, 29, false, null, false, null, '{"fields":[{"key":"itens","label":"Quais utiliza?","type":"multiselect","required":true,"options":["Whey protein ou outra proteína","Creatina","Cafeína","Gel de carboidrato","Bebida esportiva","Eletrólitos ou cápsulas de sal","Multivitamínico","Ferro","Vitamina D","Vitamina B12","Ômega-3","Probiótico","Fitoterápico","Outro","Não utilizo"]},{"key":"detalhes","label":"Detalhes por item","type":"structured_list","addLabel":"Adicionar suplemento","show_if":{"key":"self.itens","op":"includes_any","value":["Whey protein ou outra proteína","Creatina","Cafeína","Gel de carboidrato","Bebida esportiva","Eletrólitos ou cápsulas de sal","Multivitamínico","Ferro","Vitamina D","Vitamina B12","Ômega-3","Probiótico","Fitoterápico","Outro"]},"fields":[{"key":"produto","label":"Produto","type":"text","required":true},{"key":"marca","label":"Marca","type":"text"},{"key":"quantidade","label":"Quantidade","type":"text"},{"key":"horario","label":"Horário","type":"text"},{"key":"frequencia","label":"Frequência","type":"text"},{"key":"quem_recomendou","label":"Quem recomendou","type":"text"}]}]}'::jsonb, null),
      (v_form, '6. Alimentação habitual', 'Frequência de consumo de grupos alimentares', 'frequency_grid', null, 'frequencia_alimentar', null, null, null, false, 30, false, null, false, null, '{"rows":["Frutas","Verduras e legumes","Feijão, lentilha, ervilha ou grão-de-bico","Leite, iogurte ou queijo","Bebida vegetal fortificada","Ovos","Carne bovina","Frango","Peixes ou sardinha","Castanhas, amendoim ou pasta de amendoim","Chia, linhaça ou outras sementes","Aveia ou cereais integrais","Produtos ultraprocessados","Bebidas alcoólicas"],"columns":["Nunca","Menos de uma vez por semana","Uma a duas vezes por semana","Três a quatro vezes por semana","Cinco a seis vezes por semana","Uma vez ao dia","Duas ou mais vezes ao dia"]}'::jsonb, null),
      (v_form, '7. Comportamento alimentar', 'Agora, sobre a sua relação com a comida. Responda pensando nas últimas duas semanas. Não existe nota boa ou ruim: o objetivo é a gente comparar como você está hoje com como vai estar ao longo do programa.', 'info', 'info', 'aval_abertura', null, null, null, false, 31, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Quanto você entende hoje por que come do jeito que come?', 'scale', 'scale', 'aval_entende_por_que_come', null, 0, 10, true, 32, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Quanto você sente que está no controle das suas escolhas com a comida?', 'scale', 'scale', 'aval_controle_escolhas', null, 0, 10, true, 33, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Quanto a comida ocupa a sua cabeça em um dia comum?', 'scale', 'scale', 'aval_comida_na_cabeca', null, 0, 10, true, 34, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Quanto de culpa você sente depois de comer algo fora do que planejou?', 'scale', 'scale', 'aval_culpa', null, 0, 10, true, 35, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Quanto você confia que consegue manter o que conquistou sem depender de ninguém?', 'scale', 'scale', 'aval_autonomia', null, 0, 10, true, 36, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Quanto o seu comer está te ajudando a treinar e a se recuperar bem?', 'scale', 'scale', 'aval_comer_e_treino', null, 0, 10, true, 37, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Como está a sua relação com o seu corpo e com o seu peso?', 'scale', 'scale', 'aval_corpo_e_peso', null, 0, 10, true, 38, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'Em uma frase, como você descreveria a sua relação com a comida hoje?', 'textarea', 'long_text', 'aval_relacao_em_uma_frase', null, null, null, false, 39, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'O que te trouxe ao Metanóia?', 'textarea', 'long_text', 'aval_o_que_mudou', null, null, null, false, 40, false, null, false, null, null, 'comportamental'),
      (v_form, '7. Comportamento alimentar', 'O que você gostaria que fosse diferente ao final das 12 semanas?', 'textarea', 'long_text', 'aval_o_que_falta', null, null, null, false, 41, false, null, false, null, null, 'comportamental'),
      (v_form, '8. Observações', 'Observações adicionais', 'textarea', 'long_text', 'observacoes_adicionais', null, null, null, false, 42, false, null, false, null, null, null);

    perform public.publish_anamnese_form_version(v_form, 'Metanóia: Anamnese Completa, blocos do app e seção comportamental, versão inicial');
  end if;
end $$;
